# variable "aws_region" {}
# variable "az_1" {}
# variable "az_2" {}
# variable "aws_instance" {}
# variable "ami_id" {}
# variable "aws_vpc" {}
# variable "aws_subnet_1" {}
# variable "aws_subnet_2" {}
# variable "aws_db_instance" {}
# variable "db_username" {}
# variable "db_password" {}
# variable "db_name" {}
# variable "db_allocated_storage" {}
# variable "db_identifier" {}
# variable "db_engine" {}
# variable "instance_class" {}
# variable "vpc_cidr_block" {}
# variable "subnet_1_cidr_block" {}
# variable "subnet_2_cidr_block" {}
# variable "vpc_name" {}
# variable "aws_db_subnet_group" {}
# variable "bucket_name" {}
# variable "instance_tags" {}

