variable "subnet_1_id" {}
variable "subnet_2_id" {}
variable "instance_class" {}
variable "db_name" {}
variable "username" {}
variable "password" {}
variable "db_allocated_storage" {}
variable "db_identifier" {}
variable "engine" {}
